version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbopen
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local